Repository dajudge/kindcontainer, pull requests merged in 2024-02, with the labels that each got.

#256 Fixing links to JUnit 4 examples.
  README.md
Labels: bug, documentation

#268 Bump Helm3Container to `alpine/helm:3.14.0`
  README.md
  src/main/java/com/dajudge/kindcontainer/KubernetesContainer.java
Labels: enhancement, type/dependency

#265 Support for passing values as file in Helm
  src/main/java/com/dajudge/kindcontainer/helm/InstallFluent.java
  src/test/java/com/dajudge/kindcontainer/Helm3Test.java
  src/test/resources/hello-values.yaml
Labels: enhancement

#269 Add support for 1.29.1 for `KindContainer`
  k8s-versions.json
  src/main/java/com/dajudge/kindcontainer/KindContainer.java
Labels: enhancement

#270 Add support for 1.29.1 for `K3sContainer`
  k8s-versions.json
Labels: enhancement

#271 Add support for 1.29.1 for `ApiServerContainer`
  k8s-versions.json
Labels: enhancement

#273 Use newer Etcd version
  README.md
  src/main/java/com/dajudge/kindcontainer/ApiServerContainer.java
Labels: enhancement, type/dependency
